name: CI

on:
  push:
    branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build UCG static library
        run: ./build.sh

      - name: Run tests
        run: |
          cd tests/
          ./build_and_run.sh
